/**
 * Regime profile and probability layers — port of `marketRegimeProfile`,
 * `regimeActionLines`, `probabilityLayer` and both `applyProbabilityLayer` overloads in
 * `ChartGPT/MarketAnalysisEngine.swift` (lines ~1041-1556).
 *
 * `probabilityLayer` produces the scenario percentages and the "Probability layer: …"
 * risk note. iOS reads the risk mode from UserDefaults as ambient state; here it is an
 * explicit parameter, because a stateless engine is the only way to run several risk
 * modes in one process (and the server handles many users at once).
 *
 * PARITY NOTE: `full_snapshot_expected_ios_v1.json` was generated by a test that sets
 * `onboarding.riskMode`, while the engine reads `analysis.strategy.riskMode`. The three
 * risk-mode variants in that fixture are therefore byte-identical and only pin the
 * `balanced` path. Conservative and aggressive are ported from the source but are NOT
 * covered by the golden suite.
 */

import { formatF, prefix, rounded, toInt } from "./swift";
import type { ADXPack, Bias, Scenario, StrategyRiskMode, TradeSetup, VolatilityRegime } from "./types";
import type { MarketStructureLayer } from "./structure";

export type RegimeProfileKind =
  | "trendingUp"
  | "trendingDown"
  | "ranging"
  | "compression"
  | "breakoutExpansion"
  | "highVolatility"
  | "exhaustion"
  | "reversal"
  | "unclear";

/** Swift: `MarketRegimeProfile.Kind` raw values, which surface in user-visible text. */
export const regimeKindLabel: Record<RegimeProfileKind, string> = {
  trendingUp: "Trending up",
  trendingDown: "Trending down",
  ranging: "Range / chop",
  compression: "Compression",
  breakoutExpansion: "Breakout expansion",
  highVolatility: "High volatility",
  exhaustion: "Exhaustion",
  reversal: "Reversal environment",
  unclear: "Unclear"
};

export interface MarketRegimeProfile {
  kind: RegimeProfileKind;
  confidence: number;
  characteristics: string[];
  implication: string;
}

export interface ProbabilityLayer {
  bullish: number;
  bearish: number;
  range: number;
  trap: number;
  pullbackRisk: string;
  riskMode: StrategyRiskMode;
  riskLabel: string;
}

/** Swift: `ProbabilityLayer.riskNote`. */
export function probabilityRiskNote(layer: ProbabilityLayer): string {
  return `Probability layer: bullish ${layer.bullish}% • bearish ${layer.bearish}% • range ${layer.range}% • trap ${layer.trap}% • pullback risk ${layer.pullbackRisk} • risk ${layer.riskLabel}`;
}

export interface RegimeProfileInput {
  regimeLabel: string;
  regimeConfidence: number | null;
  structure: string;
  structureLayer: MarketStructureLayer;
  trendStrength: number | null;
  volatilityPct: number | null;
  volatilityRegime: VolatilityRegime | null;
  adxValue: number | null;
  plusDI: number | null;
  minusDI: number | null;
  rsi14: number | null;
  stochK: number | null;
  volumeState: string;
}

/** Swift: `marketRegimeProfile(...)`. */
export function marketRegimeProfile(input: RegimeProfileInput): MarketRegimeProfile {
  const {
    regimeLabel,
    regimeConfidence,
    structure,
    structureLayer,
    trendStrength,
    volatilityPct,
    volatilityRegime,
    adxValue,
    plusDI,
    minusDI,
    rsi14,
    stochK,
    volumeState
  } = input;

  const regime = regimeLabel.toLowerCase();
  const structureText =
    `${structure} ${structureLayer.swingLabel} ${structureLayer.events.join(" ")}`.toLowerCase();
  const strength = Math.abs(trendStrength ?? 0);
  const adx = adxValue ?? 0;
  const highVolatility =
    volatilityRegime?.label.toLowerCase().includes("high") === true || (volatilityPct ?? 0) >= 2.5;
  const lowVolatility =
    volatilityRegime?.label.toLowerCase().includes("low") === true || (volatilityPct ?? 999) <= 0.65;
  const volumeLower = volumeState.toLowerCase();
  const weakVolume =
    volumeLower.includes("low") || volumeLower.includes("synthetic") || volumeLower.includes("not available");
  const elevatedVolume = volumeLower.includes("high") || volumeLower.includes("elevated");
  const rangeEvidenceCount = [
    regime.includes("range") || regime.includes("consolidation"),
    structureLayer.isRangeLike || structureText.includes("range"),
    structureText.includes("mixed") || structureText.includes("transition"),
    adx > 0 && adx < 18,
    strength < 0.08
  ].filter(Boolean).length;
  const rangeLike = rangeEvidenceCount >= 2;
  const compressionLike = lowVolatility && adx > 0 && adx < 16 && strength < 0.12 && (rangeLike || weakVolume);
  const bullishDirection =
    regime.includes("bullish trend") ||
    regime.includes("bullish rebound") ||
    regime.includes("bullish reversal") ||
    structureLayer.bias === "bullish" ||
    (plusDI ?? 0) > (minusDI ?? 0) + 1.0;
  const bearishDirection =
    regime.includes("bearish trend") ||
    regime.includes("bearish pullback") ||
    regime.includes("bearish reversal") ||
    structureLayer.bias === "bearish" ||
    (minusDI ?? 0) > (plusDI ?? 0) + 1.0;
  const exhaustionLike =
    ((rsi14 ?? 50) >= 74 && (stochK ?? 50) >= 88) ||
    ((rsi14 ?? 50) <= 26 && (stochK ?? 50) <= 12) ||
    regime.includes("exhaust");
  const expansionLike =
    highVolatility &&
    elevatedVolume &&
    adx >= 20 &&
    (structureLayer.hasBullishBOS || structureLayer.hasBearishBOS || structureText.includes("bos"));
  const reversalLike =
    regime.includes("reversal") ||
    structureLayer.hasBullishCHoCH ||
    structureLayer.hasBearishCHoCH ||
    structureLayer.hasBullishSweep ||
    structureLayer.hasBearishSweep;

  let kind: RegimeProfileKind;
  if (exhaustionLike) {
    kind = "exhaustion";
  } else if (expansionLike) {
    kind = "breakoutExpansion";
  } else if (reversalLike) {
    kind = "reversal";
  } else if (compressionLike) {
    kind = "compression";
  } else if (rangeLike || (adx > 0 && adx < 16 && strength < 0.06)) {
    kind = "ranging";
  } else if (highVolatility) {
    kind = "highVolatility";
  } else if (bullishDirection && !bearishDirection) {
    kind = "trendingUp";
  } else if (bearishDirection && !bullishDirection) {
    kind = "trendingDown";
  } else {
    kind = "unclear";
  }

  const characteristics: string[] = [];
  if (adx > 0) {
    characteristics.push(`Regime input: ADX ${toInt(rounded(adx))}`);
  }
  if (trendStrength !== null) {
    characteristics.push(`Regime input: trend strength ${formatF(trendStrength, 2)}`);
  }
  if (volatilityRegime !== null) {
    characteristics.push(`Regime input: volatility ${volatilityRegime.label}`);
  }
  if (structureLayer.isRangeLike) {
    characteristics.push("Regime input: overlapping/range-like structure");
  }
  if (structureLayer.hasBullishBOS || structureLayer.hasBearishBOS) {
    characteristics.push("Regime input: break of structure detected");
  }
  if (weakVolume) {
    characteristics.push("Regime input: weak volume confirmation");
  } else if (elevatedVolume) {
    characteristics.push("Regime input: elevated volume participation");
  }

  const implication = ((): string => {
    switch (kind) {
      case "trendingUp":
        return "Preferred: bullish pullbacks/continuation. Penalized: countertrend shorts and range fades without rejection.";
      case "trendingDown":
        return "Preferred: bearish pullbacks/rejections. Penalized: countertrend longs and bottom-fishing without reclaim.";
      case "ranging":
        return "Preferred: range rotations/reclaims. Avoid: breakout chasing until price accepts outside the range.";
      case "compression":
        return "Preferred: confirmed break-and-hold after volume expansion. Avoid: early breakout chasing inside compression.";
      case "breakoutExpansion":
        return "Preferred: breakout continuation after retest holds. Penalized: mean reversion against expansion.";
      case "highVolatility":
        return "Preferred: confirmation-based setups with wider invalidation. Avoid: tight stops and late entries.";
      case "exhaustion":
        return "Preferred: pullback/reversal confirmation. Avoid: late continuation/FOMO entries.";
      case "reversal":
        return "Preferred: reclaim/breakdown confirmation. Penalized: stale continuation in the old trend.";
      default:
        return "Preferred: wait/no-edge. Avoid: forcing direction before structure, volume, or HTF confirms.";
    }
  })();

  let confidence = regimeConfidence ?? 45;
  switch (kind) {
    case "breakoutExpansion":
      confidence += elevatedVolume ? 10 : 4;
      confidence += adx >= 25 ? 8 : 0;
      break;
    case "compression":
      confidence += lowVolatility ? 10 : 0;
      confidence += rangeLike ? 6 : 0;
      break;
    case "ranging":
      confidence += rangeLike ? 8 : 0;
      confidence -= highVolatility ? 5 : 0;
      break;
    case "exhaustion":
      confidence += exhaustionLike ? 12 : 0;
      break;
    case "trendingUp":
    case "trendingDown":
      confidence += adx >= 22 ? 8 : 0;
      confidence += strength >= 0.1 ? 6 : 0;
      break;
    case "highVolatility":
      confidence += highVolatility ? 10 : 0;
      break;
    case "reversal":
      confidence += reversalLike ? 8 : 0;
      break;
    case "unclear":
      confidence = Math.min(confidence, 55);
      break;
  }

  return {
    kind,
    confidence: toInt(rounded(Math.min(Math.max(confidence, 10), 95))),
    characteristics: prefix([...characteristics, ...regimeActionLines(kind)], 8),
    implication
  };
}

/** Swift: `regimeActionLines(for:)`. */
export function regimeActionLines(kind: RegimeProfileKind): string[] {
  switch (kind) {
    case "trendingUp":
      return [
        "Regime preferred: bullish pullbacks / continuation",
        "Regime penalized: countertrend shorts",
        "Regime trap risk: normal unless extended"
      ];
    case "trendingDown":
      return [
        "Regime preferred: bearish pullbacks / rejections",
        "Regime penalized: countertrend longs",
        "Regime trap risk: normal unless oversold"
      ];
    case "ranging":
      return [
        "Regime preferred: mean reversion / range fades",
        "Regime penalized: breakout continuation",
        "Regime trap risk: elevated"
      ];
    case "compression":
      return [
        "Regime preferred: confirmed break-and-hold",
        "Regime penalized: early breakout chasing",
        "Regime trap risk: high until expansion confirms"
      ];
    case "breakoutExpansion":
      return [
        "Regime preferred: continuation after retest",
        "Regime penalized: mean reversion against expansion",
        "Regime trap risk: moderate"
      ];
    case "highVolatility":
      return [
        "Regime preferred: confirmation with wider invalidation",
        "Regime penalized: tight-stop entries",
        "Regime trap risk: elevated"
      ];
    case "exhaustion":
      return [
        "Regime preferred: pullback / reversal confirmation",
        "Regime penalized: late continuation",
        "Regime trap risk: high"
      ];
    case "reversal":
      return [
        "Regime preferred: reclaim / breakdown confirmation",
        "Regime penalized: stale continuation",
        "Regime trap risk: elevated"
      ];
    default:
      return [
        "Regime preferred: wait / no-edge",
        "Regime penalized: forced direction",
        "Regime trap risk: elevated"
      ];
  }
}

/** Swift: `probabilityRiskLabel(_:)`. */
export function probabilityRiskLabel(riskMode: StrategyRiskMode): string {
  switch (riskMode) {
    case "conservative":
      return "Low";
    case "aggressive":
      return "High";
    default:
      return "Medium";
  }
}

export interface ProbabilityLayerInput {
  regimeLabel: string;
  regimeProfile: MarketRegimeProfile;
  structureLayer: MarketStructureLayer;
  bias: Bias | null;
  rsi14: number | null;
  stochK: number | null;
  macdHist: number | null;
  adx: ADXPack;
  volumeState: string;
  volatilityRegime: VolatilityRegime | null;
  /** iOS reads this from UserDefaults ("analysis.strategy.riskMode"); passed explicitly here. */
  riskMode: StrategyRiskMode;
}

/**
 * Swift: `probabilityLayer(...)`.
 *
 * Starts from a 33/33/34 prior and nudges it with the bias split, regime, structure
 * events and oscillators, then clamps and renormalises the three directional buckets to
 * 100%. `trap` is deliberately NOT part of that normalisation — it is an independent
 * measure that the setup-level note later carves out of the 100%.
 */
export function probabilityLayer(input: ProbabilityLayerInput): ProbabilityLayer {
  const {
    regimeLabel,
    regimeProfile,
    structureLayer,
    bias,
    rsi14,
    stochK,
    macdHist,
    adx,
    volumeState,
    volatilityRegime,
    riskMode
  } = input;

  const regime = regimeLabel.toLowerCase();
  let bullish = 33.0;
  let bearish = 33.0;
  let range = 34.0;
  let trap = 8.0;

  const biasBull = bias?.bullish ?? 0;
  const biasBear = bias?.bearish ?? 0;
  bullish += (biasBull - biasBear) * 0.22;
  bearish += (biasBear - biasBull) * 0.22;

  if (regime.includes("bullish trend") || regime.includes("bullish rebound")) {
    bullish += 12;
    range -= 6;
  } else if (regime.includes("bearish trend") || regime.includes("bearish pullback")) {
    bearish += 12;
    range -= 6;
  } else if (regime.includes("range") || regime.includes("consolidation")) {
    range += 16;
    bullish -= 5;
    bearish -= 5;
  } else if (regime.includes("reversal")) {
    trap += 5;
  }

  switch (regimeProfile.kind) {
    case "trendingUp":
      bullish += 8;
      bearish -= 4;
      range -= 5;
      break;
    case "trendingDown":
      bearish += 8;
      bullish -= 4;
      range -= 5;
      break;
    case "ranging":
      range += 14;
      bullish -= 4;
      bearish -= 4;
      trap += 4;
      break;
    case "compression":
      range += 12;
      trap += 8;
      bullish -= 3;
      bearish -= 3;
      break;
    case "breakoutExpansion":
      range -= 8;
      trap = Math.max(4, trap - 2);
      if (structureLayer.bias === "bullish") {
        bullish += 10;
      } else if (structureLayer.bias === "bearish") {
        bearish += 10;
      }
      break;
    case "highVolatility":
      trap += 7;
      range += 2;
      break;
    case "exhaustion":
      trap += 12;
      range += 5;
      bullish -= regime.includes("bullish") ? 3 : 0;
      bearish -= regime.includes("bearish") ? 3 : 0;
      break;
    case "reversal":
      trap += 7;
      range += 4;
      break;
    case "unclear":
      range += 8;
      trap += 4;
      break;
  }

  switch (structureLayer.bias) {
    case "bullish":
      bullish += 10;
      bearish -= 5;
      range -= 3;
      break;
    case "bearish":
      bearish += 10;
      bullish -= 5;
      range -= 3;
      break;
    default:
      range += 6;
      break;
  }
  if (structureLayer.hasBullishBOS) {
    bullish += 7;
    range -= 3;
  }
  if (structureLayer.hasBearishBOS) {
    bearish += 7;
    range -= 3;
  }
  if (structureLayer.hasBullishCHoCH) {
    bullish += 5;
    trap += 2;
  }
  if (structureLayer.hasBearishCHoCH) {
    bearish += 5;
    trap += 2;
  }
  if (structureLayer.hasBullishSweep || structureLayer.hasBearishSweep) {
    trap += 7;
    range += 3;
  }
  if (structureLayer.hasBullishReclaim || structureLayer.hasBullishReaction) bullish += 4;
  if (structureLayer.hasBearishReclaim || structureLayer.hasBearishReaction) bearish += 4;
  if (structureLayer.isRangeLike) {
    range += 10;
    trap += 3;
  }

  if (macdHist !== null) {
    if (macdHist > 0) bullish += 4;
    else if (macdHist < 0) bearish += 4;
  }
  if (adx.adx !== null) {
    const adxValue = adx.adx;
    if (adxValue >= 25) {
      range -= 5;
      if ((adx.plusDI ?? 0) >= (adx.minusDI ?? 0)) bullish += 4;
      else bearish += 4;
    } else if (adxValue <= 15) {
      range += 7;
      trap += 2;
    }
  }
  if (rsi14 !== null) {
    if (rsi14 >= 72) {
      bullish += 2;
      trap += rsi14 >= 76 ? 9 : 5;
    } else if (rsi14 <= 28) {
      bearish += 2;
      trap += rsi14 <= 24 ? 9 : 5;
    } else if (rsi14 >= 55) {
      bullish += 3;
    } else if (rsi14 <= 45) {
      bearish += 3;
    }
  }
  if (stochK !== null) {
    if (stochK >= 92 || stochK <= 8) {
      trap += 7;
    } else if (stochK >= 88 || stochK <= 12) {
      trap += 4;
    }
  }

  if (rsi14 !== null && stochK !== null && ((rsi14 >= 74 && stochK >= 92) || (rsi14 <= 26 && stochK <= 8))) {
    trap += 8;
    range += 3;
  }

  const volume = volumeState.toLowerCase();
  if (volume.includes("low") || volume.includes("synthetic") || volume.includes("not available")) {
    trap += 3;
    range += 2;
  } else if (volume.includes("high")) {
    trap = Math.max(4, trap - 2);
  }

  if (volatilityRegime !== null) {
    const label = volatilityRegime.label.toLowerCase();
    if (label.includes("high")) {
      trap += 4;
    } else if (label.includes("low")) {
      range += 4;
    }
  }

  switch (riskMode) {
    case "conservative":
      trap += 3;
      range += 3;
      bullish -= bullish >= bearish ? 4 : 1;
      bearish -= bearish > bullish ? 4 : 1;
      break;
    case "balanced":
      break;
    case "aggressive":
      if (bullish >= bearish) bullish += 4;
      else bearish += 4;
      trap += 2;
      range -= 2;
      break;
  }

  bullish = Math.min(Math.max(bullish, 8), 82);
  bearish = Math.min(Math.max(bearish, 8), 82);
  range = Math.min(Math.max(range, 8), 76);
  const directionalSum = bullish + bearish + range;
  if (directionalSum > 0) {
    bullish = (bullish / directionalSum) * 100;
    bearish = (bearish / directionalSum) * 100;
    range = (range / directionalSum) * 100;
  }

  trap = Math.min(Math.max(trap, 4), 42);
  const pullbackRisk = ((): string => {
    const exhaustion =
      (rsi14 ?? 50) >= 70 || (rsi14 ?? 50) <= 30 || (stochK ?? 50) >= 85 || (stochK ?? 50) <= 15;
    if (trap >= 24 || exhaustion) return "High";
    if (trap >= 14 || structureLayer.isRangeLike) return "Moderate";
    return "Low";
  })();

  return {
    bullish: toInt(rounded(bullish)),
    bearish: toInt(rounded(bearish)),
    range: toInt(rounded(range)),
    trap: toInt(rounded(trap)),
    pullbackRisk,
    riskMode,
    riskLabel: probabilityRiskLabel(riskMode)
  };
}

/** Swift: `applyProbabilityLayer(to scenarios:probabilityLayer:)`. */
export function applyProbabilityLayerToScenarios(
  scenarios: readonly Scenario[],
  layer: ProbabilityLayer
): Scenario[] {
  return scenarios.map((scenario) => {
    const name = scenario.name.toLowerCase();
    let probability: number;
    if (name.includes("bull")) {
      probability = layer.bullish;
    } else if (name.includes("bear")) {
      probability = layer.bearish;
    } else {
      probability = layer.range;
    }
    return { ...scenario, probability };
  });
}

/**
 * Swift: `applyProbabilityLayer(to setups:probabilityLayer:)`.
 * Re-expresses the directional split as continuation/reversal shares of whatever the trap
 * percentage leaves over, then appends it as a note.
 */
export function applyProbabilityLayerToSetups(
  setups: readonly TradeSetup[],
  layer: ProbabilityLayer
): TradeSetup[] {
  return setups.map((setup) => {
    const direction = setup.direction.toLowerCase();
    let continuation: number;
    let reversal: number;
    if (direction.includes("bull")) {
      continuation = layer.bullish;
      reversal = layer.bearish;
    } else if (direction.includes("bear")) {
      continuation = layer.bearish;
      reversal = layer.bullish;
    } else {
      continuation = layer.range;
      reversal = Math.max(layer.bullish, layer.bearish);
    }

    const updated: TradeSetup = {
      ...setup,
      notes: [...setup.notes],
      rationale: [...setup.rationale],
      targets: [...setup.targets]
    };
    const trap = layer.trap;
    const continuationShare = Math.max(0, continuation);
    const reversalShare = Math.max(0, reversal);
    const directionalTotal = Math.max(continuationShare + reversalShare, 1);
    const remaining = Math.max(0, 100 - trap);
    const normalizedContinuation = toInt(rounded((continuationShare / directionalTotal) * remaining));
    const normalizedReversal = Math.max(0, 100 - trap - normalizedContinuation);
    const note = `Probability: continuation ${normalizedContinuation}% • reversal ${normalizedReversal}% • trap ${trap}% • pullback risk ${layer.pullbackRisk} • risk ${layer.riskLabel}`;
    if (!updated.notes.includes(note)) {
      updated.notes.push(note);
    }
    return updated;
  });
}
